### ISSUE TITLE
Tests fail?

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubihsmrs#5]
It looks like this crate does not use `YUBIHSM_PKCS11_CONF` env variable, and is unable to figure how to connect to the YubiHSM2 device?

```
$ cargo test --lib
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running target/debug/deps/yubihsmrs-bc691c75abc09ef1

running 16 tests
test error::tests::check_errors ... ok
test test::import_authkey ... FAILED
test test::delete_object ... FAILED
test test::get_object_info ... FAILED
test test::delete_object_twice ... FAILED
test test::generate_asymmetric_key ... FAILED
test test::retried_session_expiration ... ignored
test test::simple_session_expiration ... ignored
test test::string_conversions ... ok
test test::device_info ... FAILED
test test::export_wrapped ... FAILED
test test::establish_seventeen_sessions ... FAILED
test test::import_wrap_key ... FAILED
test test::import_wrapped ... FAILED
test test::import_opaque ... FAILED
test test::list_objects ... FAILED

failures:

---- test::import_authkey stdout ----
thread 'test::import_authkey' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- test::delete_object stdout ----
thread 'test::delete_object' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::get_object_info stdout ----
thread 'test::get_object_info' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::delete_object_twice stdout ----
thread 'test::delete_object_twice' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::generate_asymmetric_key stdout ----
thread 'test::generate_asymmetric_key' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::device_info stdout ----
thread 'test::device_info' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::export_wrapped stdout ----
thread 'test::export_wrapped' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::establish_seventeen_sessions stdout ----
thread 'test::establish_seventeen_sessions' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::import_wrap_key stdout ----
thread 'test::import_wrap_key' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::import_wrapped stdout ----
thread 'test::import_wrapped' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::import_opaque stdout ----
thread 'test::import_opaque' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5

---- test::list_objects stdout ----
thread 'test::list_objects' panicked at 'Unable to create HSM with connector: LibYubiHsm(ConnectorNotFound)', src/libcore/result.rs:997:5


failures:
    test::delete_object
    test::delete_object_twice
    test::device_info
    test::establish_seventeen_sessions
    test::export_wrapped
    test::generate_asymmetric_key
    test::get_object_info
    test::import_authkey
    test::import_opaque
    test::import_wrap_key
    test::import_wrapped
    test::list_objects

test result: FAILED. 2 passed; 12 failed; 2 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
$
```

Also, I assume that it can handle `https://` connector (since `yubihsm-shell` and `yubihsm-connector` do it fine)? 

Here's my `~/yubihsm_pkcs11.conf` file:
```
$ cat ~/yubihsm_pkcs11.conf
# URL of the connector to use. This can be a comma-separated list
connector = https://myhostname.mydomain:12345

# Enables general debug output in the module
#debug

# Enables function tracing (ingress/egress) debug output in the module
# dinout

# Redirects the debug output to a specific file.
#debug-file = /tmp/yubihsm_pkcs11_debug.txt

# CA certificate to use for HTTPS validation. 
cacert = /opt/local/share/curl/curl-ca-bundle.crt
```

**Comment by a-dma** [comment]
This library has noting to do with (and knows nothing about) PKCS#11. It simply provides Rust bindings to libyubihsm, linking against it.

It looks like you don't have a connector running as hinted by the `LibYubiHsm(ConnectorNotFound)` error.
Try starting one or using direct USB.

**Comment by mouse07410** [comment]
> It looks like you don't have a connector running ... Try starting one ...

Is this proof enough that the connector is running?
```
$ yhsm2-shell -a get-device-info
Session keepalive set up to run every 15 seconds
Version number:		2.0.0
Serial number:		75xxxxx
Log used:		62/62
Supported algorithms:	rsa-pkcs1-sha1, rsa-pkcs1-sha256, rsa-pkcs1-sha384, 
			rsa-pkcs1-sha512, rsa-pss-sha1, rsa-pss-sha256, 
			rsa-pss-sha384, rsa-pss-sha512, rsa2048, 
			rsa3072, rsa4096, ecp256, 
			ecp384, ecp521, eck256, 
			ecbp256, ecbp384, ecbp512, 
			hmac-sha1, hmac-sha256, hmac-sha384, 
			hmac-sha512, ecdsa-sha1, ecdh, 
			rsa-oaep-sha1, rsa-oaep-sha256, rsa-oaep-sha384, 
			rsa-oaep-sha512, aes128-ccm-wrap, opaque-data, 
			opaque-x509-certificate, mgf1-sha1, mgf1-sha256, 
			mgf1-sha384, mgf1-sha512, template-ssh, 
			aes128-yubico-otp, aes128-yubico-authentication, aes192-yubico-otp, 
			aes256-yubico-otp, aes192-ccm-wrap, aes256-ccm-wrap, 
			ecdsa-sha256, ecdsa-sha384, ecdsa-sha512, 
			ed25519, ecp224, 
$
```

But I concur that this library appears unable to find it. Could you help with figuring out why it couldn't and remedying it?

**Comment by a-dma** [comment]
Is your connector running at `https://myhostname.mydomain:12345`? If so then the tests won't be able to find the connector, they expect it to be running at `http://127.0.0.1:12345` or over direct USB if you set the environment variable `YUBIHSM_DIRECT_USB` before you run `cargo test`.

Make sure to use `--test-threads=1` or you will get failures when opening the device multiple times.

**Comment by mouse07410** [comment]
> Is your connector running at `https://myhostname.mydomain:12345?`

Yes it is.

> If so then the tests won't be able to find the connector, they expect it to be running at `http://127.0.0.1:12345` or over direct USB

How to teach it to find it where the config file says it is?

**Comment by a-dma** [comment]
What config file are you referring to? The tests don't support any config file.
If you mean `yubihsm_pkcs11.conf` then that's the configuration for the PKCS#11 module, which has nothing to do with this library or its tests.

The tests use https://github.com/Yubico/yubihsmrs/blob/master/src/lib.rs#L576.

**Comment by mouse07410** [comment]
> If you mean `yubihsm_pkcs11.conf` then that's the configuration for the PKCS#11 module, which has nothing to do with this library or its tests.

Yes, you are correct. I missed that, sorry.

However, I still want to get it working with the currently running connector. Would replacing https://github.com/Yubico/yubihsmrs/blob/cb65227c605e57ba7fa1347a20010f21366f3a08/src/lib.rs#L551 with my FQDN help?

**Comment by a-dma** [comment]
It would, but only in your specific case. I've pushed a change.
Try setting `YUBIHSM_CONNECTOR_URL` to your connector before running the tests.

**Comment by mouse07410** [comment]
With the latest master:
```
$ export YUBIHSM_CONNECTOR_URL=https://549725-mitll.llan.ll.mit.edu:12345
$ $ cargo test --lib -- --test-threads=1
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running target/debug/deps/yubihsmrs-bc691c75abc09ef1

running 16 tests
test error::tests::check_errors ... ok
test test::delete_object ... FAILED
test test::delete_object_twice ... FAILED
test test::device_info ... ok
test test::establish_seventeen_sessions ... FAILED
test test::export_wrapped ... FAILED
test test::generate_asymmetric_key ... FAILED
test test::get_object_info ... FAILED
test test::import_authkey ... FAILED
test test::import_opaque ... FAILED
test test::import_wrap_key ... FAILED
test test::import_wrapped ... FAILED
test test::list_objects ... FAILED
test test::retried_session_expiration ... ignored
test test::simple_session_expiration ... ignored
test test::string_conversions ... ok

failures:

---- test::delete_object stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(CryptogramMismatch)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- test::delete_object_twice stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(CryptogramMismatch)', src/libcore/result.rs:997:5

---- test::establish_seventeen_sessions stdout ----
i is 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(CryptogramMismatch)', src/libcore/result.rs:997:5

---- test::export_wrapped stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(CryptogramMismatch)', src/libcore/result.rs:997:5

---- test::generate_asymmetric_key stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(CryptogramMismatch)', src/libcore/result.rs:997:5

---- test::get_object_info stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5

---- test::import_authkey stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5

---- test::import_opaque stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5

---- test::import_wrap_key stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5

---- test::import_wrapped stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5

---- test::list_objects stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibYubiHsm(DeviceSessionsFull)', src/libcore/result.rs:997:5


failures:
    test::delete_object
    test::delete_object_twice
    test::establish_seventeen_sessions
    test::export_wrapped
    test::generate_asymmetric_key
    test::get_object_info
    test::import_authkey
    test::import_opaque
    test::import_wrap_key
    test::import_wrapped
    test::list_objects

test result: FAILED. 3 passed; 11 failed; 2 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
$
```

**Comment by a-dma** [comment]
What version of libyubihsm are you linking against? Is there anything else trying to open sessions with the device?

Try power-cycling the device to make sure there are no open sessions, or run fewer tests with something like `cargo test -- --test-threads=1 delete`

**Comment by mouse07410** [comment]
> What version of `libyubihsm` are you linking against? 

Current/latest.

> Is there anything else trying to open sessions with the device?

I don't know - probably not. But it is not a blank device - it has configured passwords, asymmetric and auth keys, and performs some functionality (remote signatures upon request). I'm reasonably sure there are no other requests *when I'm trying the tests*.

Could you say a few words about what tests does `cargo test` run in this case, what they are supposed to do to the device, and what state the device is supposed to be in before the tests start and after the tests are finished.

Also, if the device has a current state now, and I'd like to preserve it for after the tests - how do you recommend for me to store/save it? It's YubiHSM2-2.0.0.

**Comment by a-dma** [comment]
You can find the tests at https://github.com/Yubico/yubihsmrs/blob/master/src/lib.rs#L538.

Most of them are invasive, in the sense that they require writing and deleting objects to test specific functionalities. Currently non of them are destructive, but that may change in the future.

If you deleted or modified the default Authentication key, that would explain the Cryptogram Mismatch errors.

The best way to backup the device is to export all the objects that you care about under wrap to an imported Wrapping key that you have stored elsewhere so that you can restore it later.

**Comment by aveenismail** [comment]
Closing this ticket for lack of activity

**Comment by mouse07410** [comment]
What activity do you expect? 

A problem was reported - the maintainers should fix the problem, or ask for specific info if needed. 

AFAICT, neither was done.
